Config option to disable dolly stacking
GTNewHorizons/Jabba pull request #32
Opened 2024-05-21 17:29 UTC by brandyyn

It is disabled as default, dollies are way too powerful to carry so many dollies out on your adventures in my pack

2024-05-21 17:30 UTC, chochem commented
I dont know about that default.
At the least you will need to turn it on in the GTNH config repo as we want the feature here.

2024-05-21 17:32 UTC, chochem commented
ah wait. judging by the code you mean that the disabling is disabled by default? XD

2024-05-21 17:33 UTC, ah-OOG-ah commented
The config is disabled by default, and the feature is *disabling* folded dollies. So confusing double negative, but it doesn't change current behavior.

2024-05-21 17:36 UTC, brandyyn commented
> I dont know about that default. At the least you will need to turn it on in the GTNH config repo as we want the feature here.

the config option is disabled by default; sorry i didn't think of the double negative. enabling the config will turn off the ability to collapse dollies

2024-05-26 08:20 UTC, OneEyeMaker requested changes
Good feature.
Just improve configuration naming to prevent even more confusion.

2024-05-26 08:20 UTC, OneEyeMaker commented on src/main/java/mcp/mobius/betterbarrels/BetterBarrels.java
> +    public static boolean DisableStacking;
nitpick: Please, use `lowerCamelCase`  and more descriptive name. Current name sounds like this config disables stacking of items inside barrel.
```suggestion
    public static boolean disableDollyStacking;
```

2024-05-26 08:20 UTC, OneEyeMaker commented on src/main/java/mcp/mobius/betterbarrels/BetterBarrels.java
> +            DisableStacking = config.getBoolean("DisableStacking", Configuration.CATEGORY_GENERAL, false, "Disables the ability to collapse and stack the dollies");
Same for configuration name

2024-05-27 10:44 UTC, brandyyn commented
better?

2024-05-27 12:55 UTC, OneEyeMaker approved these changes

2024-05-27 12:56 UTC, merged